---
- name: Create the folders
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ item }}"
    state: directory
    owner: root
    group: 101
    mode: 0770
  loop:
    - bunkerweb/
    - bunkerweb/data

- name: Copy the env file
  ansible.builtin.template:
    src: env.j2
    owner: root
    group: 101
    mode: 0644
    dest: "{{ docker_dir }}/bunkerweb/.env"

- name: Make sure the Bunkerweb container is created and running
  register: bunkerweb_result
  retries: 5
  until: bunkerweb_result is succeeded
  community.general.docker_container:
    name: "bunkerweb"
    image: "bunkerity/bunkerweb:{{ bunkerweb_version }}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      start_period: 10s
    networks:
      - name: wg_network
        ipv4_address: 10.8.2.5
    pull: yes
    state: "started"
    env_file: "{{ docker_dir }}/bunkerweb/.env"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ docker_dir }}/bunkerweb/data:/data"
      - "/lib/modules:/lib/modules"
    restart_policy: unless-stopped

- name: Make sure the Bunkerweb-ui container is created and running
  register: bunkerweb-ui_result
  retries: 5
  until: bunkerweb-ui_result is succeeded
  community.general.docker_container:
    name: "bunkerweb-ui"
    image: "bunkerity/bunkerweb-ui:{{ bunkerweb_version }}"
    depends_on:
      - bunkerweb
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:changeme@bw-db:3306/db # Remember to set a stronger password for the database
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - name: wg_network
        ipv4_address: 10.8.2.10
    pull: yes
    state: "started"
    restart_policy: unless-stopped